// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/claims-provider.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PatreonUserId string                 `protobuf:"bytes,2,opt,name=patreon_user_id,json=patreonUserId,proto3" json:"patreon_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_claims_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetRequest) GetPatreonUserId() string {
	if x != nil {
		return x.PatreonUserId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Claims        *Claims                `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_claims_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          *Tier                  `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	PatreonUserId string                 `protobuf:"bytes,2,opt,name=patreon_user_id,json=patreonUserId,proto3" json:"patreon_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_proto_claims_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Context) GetTier() *Tier {
	if x != nil {
		return x.Tier
	}
	return nil
}

func (x *Context) GetPatreonUserId() string {
	if x != nil {
		return x.PatreonUserId
	}
	return ""
}

type Tier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tier) Reset() {
	*x = Tier{}
	mi := &file_proto_claims_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tier) ProtoMessage() {}

func (x *Tier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tier.ProtoReflect.Descriptor instead.
func (*Tier) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Tier) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Vault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        *uint64                `protobuf:"varint,1,opt,name=points,proto3,oneof" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vault) Reset() {
	*x = Vault{}
	mi := &file_proto_claims_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vault) ProtoMessage() {}

func (x *Vault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vault.ProtoReflect.Descriptor instead.
func (*Vault) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Vault) GetPoints() uint64 {
	if x != nil && x.Points != nil {
		return *x.Points
	}
	return 0
}

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Embed         *Embed                 `protobuf:"bytes,2,opt,name=embed,proto3" json:"embed,omitempty"`
	Site          *Site                  `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`
	Vault         *Vault                 `protobuf:"bytes,4,opt,name=vault,proto3" json:"vault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_proto_claims_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{5}
}

func (x *Claims) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Claims) GetEmbed() *Embed {
	if x != nil {
		return x.Embed
	}
	return nil
}

func (x *Claims) GetSite() *Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Claims) GetVault() *Vault {
	if x != nil {
		return x.Vault
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *uint64                `protobuf:"varint,1,opt,name=rate,proto3,oneof" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_proto_claims_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Connection) GetRate() uint64 {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return 0
}

type Embed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoAds         bool                   `protobuf:"varint,1,opt,name=no_ads,json=noAds,proto3" json:"no_ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embed) Reset() {
	*x = Embed{}
	mi := &file_proto_claims_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embed) ProtoMessage() {}

func (x *Embed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embed.ProtoReflect.Descriptor instead.
func (*Embed) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{7}
}

func (x *Embed) GetNoAds() bool {
	if x != nil {
		return x.NoAds
	}
	return false
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoAds         bool                   `protobuf:"varint,1,opt,name=no_ads,json=noAds,proto3" json:"no_ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_proto_claims_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claims_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_proto_claims_provider_proto_rawDescGZIP(), []int{8}
}

func (x *Site) GetNoAds() bool {
	if x != nil {
		return x.NoAds
	}
	return false
}

var File_proto_claims_provider_proto protoreflect.FileDescriptor

const file_proto_claims_provider_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/claims-provider.proto\"J\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12&\n" +
	"\x0fpatreon_user_id\x18\x02 \x01(\tR\rpatreonUserId\"R\n" +
	"\vGetResponse\x12\"\n" +
	"\acontext\x18\x01 \x01(\v2\b.ContextR\acontext\x12\x1f\n" +
	"\x06claims\x18\x02 \x01(\v2\a.ClaimsR\x06claims\"L\n" +
	"\aContext\x12\x19\n" +
	"\x04tier\x18\x01 \x01(\v2\x05.TierR\x04tier\x12&\n" +
	"\x0fpatreon_user_id\x18\x02 \x01(\tR\rpatreonUserId\"*\n" +
	"\x04Tier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x05Vault\x12\x1b\n" +
	"\x06points\x18\x01 \x01(\x04H\x00R\x06points\x88\x01\x01B\t\n" +
	"\a_points\"\x8c\x01\n" +
	"\x06Claims\x12+\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\v.ConnectionR\n" +
	"connection\x12\x1c\n" +
	"\x05embed\x18\x02 \x01(\v2\x06.EmbedR\x05embed\x12\x19\n" +
	"\x04site\x18\x03 \x01(\v2\x05.SiteR\x04site\x12\x1c\n" +
	"\x05vault\x18\x04 \x01(\v2\x06.VaultR\x05vault\".\n" +
	"\n" +
	"Connection\x12\x17\n" +
	"\x04rate\x18\x01 \x01(\x04H\x00R\x04rate\x88\x01\x01B\a\n" +
	"\x05_rate\"\x1e\n" +
	"\x05Embed\x12\x15\n" +
	"\x06no_ads\x18\x01 \x01(\bR\x05noAds\"\x1d\n" +
	"\x04Site\x12\x15\n" +
	"\x06no_ads\x18\x01 \x01(\bR\x05noAds22\n" +
	"\x0eClaimsProvider\x12 \n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_claims_provider_proto_rawDescOnce sync.Once
	file_proto_claims_provider_proto_rawDescData []byte
)

func file_proto_claims_provider_proto_rawDescGZIP() []byte {
	file_proto_claims_provider_proto_rawDescOnce.Do(func() {
		file_proto_claims_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_claims_provider_proto_rawDesc), len(file_proto_claims_provider_proto_rawDesc)))
	})
	return file_proto_claims_provider_proto_rawDescData
}

var file_proto_claims_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_claims_provider_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: GetRequest
	(*GetResponse)(nil), // 1: GetResponse
	(*Context)(nil),     // 2: Context
	(*Tier)(nil),        // 3: Tier
	(*Vault)(nil),       // 4: Vault
	(*Claims)(nil),      // 5: Claims
	(*Connection)(nil),  // 6: Connection
	(*Embed)(nil),       // 7: Embed
	(*Site)(nil),        // 8: Site
}
var file_proto_claims_provider_proto_depIdxs = []int32{
	2, // 0: GetResponse.context:type_name -> Context
	5, // 1: GetResponse.claims:type_name -> Claims
	3, // 2: Context.tier:type_name -> Tier
	6, // 3: Claims.connection:type_name -> Connection
	7, // 4: Claims.embed:type_name -> Embed
	8, // 5: Claims.site:type_name -> Site
	4, // 6: Claims.vault:type_name -> Vault
	0, // 7: ClaimsProvider.Get:input_type -> GetRequest
	1, // 8: ClaimsProvider.Get:output_type -> GetResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_claims_provider_proto_init() }
func file_proto_claims_provider_proto_init() {
	if File_proto_claims_provider_proto != nil {
		return
	}
	file_proto_claims_provider_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_claims_provider_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_claims_provider_proto_rawDesc), len(file_proto_claims_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_claims_provider_proto_goTypes,
		DependencyIndexes: file_proto_claims_provider_proto_depIdxs,
		MessageInfos:      file_proto_claims_provider_proto_msgTypes,
	}.Build()
	File_proto_claims_provider_proto = out.File
	file_proto_claims_provider_proto_goTypes = nil
	file_proto_claims_provider_proto_depIdxs = nil
}
