// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/claims-provider.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClaimsProvider_Get_FullMethodName = "/ClaimsProvider/Get"
)

// ClaimsProviderClient is the client API for ClaimsProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClaimsProviderClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type claimsProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewClaimsProviderClient(cc grpc.ClientConnInterface) ClaimsProviderClient {
	return &claimsProviderClient{cc}
}

func (c *claimsProviderClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ClaimsProvider_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClaimsProviderServer is the server API for ClaimsProvider service.
// All implementations must embed UnimplementedClaimsProviderServer
// for forward compatibility.
type ClaimsProviderServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedClaimsProviderServer()
}

// UnimplementedClaimsProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClaimsProviderServer struct{}

func (UnimplementedClaimsProviderServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClaimsProviderServer) mustEmbedUnimplementedClaimsProviderServer() {}
func (UnimplementedClaimsProviderServer) testEmbeddedByValue()                        {}

// UnsafeClaimsProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClaimsProviderServer will
// result in compilation errors.
type UnsafeClaimsProviderServer interface {
	mustEmbedUnimplementedClaimsProviderServer()
}

func RegisterClaimsProviderServer(s grpc.ServiceRegistrar, srv ClaimsProviderServer) {
	// If the following call pancis, it indicates UnimplementedClaimsProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClaimsProvider_ServiceDesc, srv)
}

func _ClaimsProvider_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClaimsProviderServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClaimsProvider_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClaimsProviderServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClaimsProvider_ServiceDesc is the grpc.ServiceDesc for ClaimsProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClaimsProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClaimsProvider",
	HandlerType: (*ClaimsProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ClaimsProvider_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/claims-provider.proto",
}
